{% set name = "swifter" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 45a26258becec4564697751fcd184b9d4554ec98d045419c53bb7decede1b511

build:
  number: 0
  skip: true  # [py27]
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - dask >=2.10.0
    - ipywidgets >=7.0.0
    - pandas >=1.0.0
    - psutil >=5.6.6
    - python
    - tqdm >=4.33.0
    - parso >0.4.0
    - bleach >=3.1.1
    - modin >=0.8.1.1
    - cloudpickle >=0.2.2

test:
  imports:
    - swifter

about:
  home: https://github.com/jmcarpenter2/swifter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A package which efficiently applies any function to a pandas dataframe or series in the fastest available manner.

extra:
  recipe-maintainers:
    - apcamargo
